### ISSUE TITLE
datepickerConnector does not support swiss date format

### ISSUE THREAD

**Issue by monp** [vaadin/vaadin-date-picker-flow#103]
Same problem as #57 and #74 but with swiss date format **dd.MM.yyyy**. Tests were done with vaadin 10.0.1.

```
DatePicker datePicker = new DatePicker();
datePicker.setLocale(new Locale("fr", "CH"));
```
**datepickerConnector.js** reports 

> "Selected locale is using unsupported date format, which might affect the parsing date."

 and later

> "Invalid value in the DatePicker."

**Comment by caalador** [comment]
Hi.

Would you have a sample that breaks the datePicker as I can't directly reproduce this with only setting the locale to `fr-CH`?

Which browser does this happen with or is it with all browsers?

**Comment by Firestorm87** [comment]
Same here.
Ust with "new Datepicker()" and VaadinSession.setLocale(new Locale("de", "DE"));

Browser newest Firefox and Chrome.

**Comment by Firestorm87** [comment]
I just debuged the connector.js:

The following Line results in an undefined targetLocaleDate for Dates in Format "dd.MM.yyyy".
let targetLocaleDate = cleanString(new Date(sample).toLocaleDateString(oldLocale).toString());

**Comment by caalador** [comment]
So the problem is that there is a warn logged to the console for an empty or non complete date string?
