### ISSUE TITLE
Label should not be cut in "Date picker with min and max" demo

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-date-picker-flow#115]
Moved from website Gitlab. Reported by Artur. 
--
https://vaadin.com/elements/vaadin-date-picker/java-examples

"Select a day within this..." should say "Select a day within this month"

Solution: Extend the width of the text area.

**Comment by web-padawan** [comment]
Fixed by #213 and will be available at https://vaadin.com as soon they update to 14.1.16 or later.
