### ISSUE TITLE
DatePicker Locale Not Working in Mobile

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-date-picker-flow#116]
_From @ugurdoksan on July 29, 2018 9:17_

### Description
DatePicker setLocale method working fine in Laptop browsers but not working in mobile phone browsers including Chrome.

### Expected outcome
When I choose the date from DatePicker from my mobile phone, it should work according to my locale.

Example (Locale TR -> Working fine in laptop browsers but not in mobile browsers):

dpStartDate = new DatePicker( "" );
dpStartDate.setPlaceholder( "Başlangıç Tarihi" );
dpStartDate.setLocale( new Locale( "tr", "TR" ) );

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

_Copied from original issue: vaadin/vaadin-date-picker#594_

**Comment by web-padawan** [comment]
Thanks for the issue. This repo is for the Web Component, and for its Java counterpart we have different repo. I will move it there so that our teammates could handle it appropriately.

**Comment by ugurdoksan** [comment]
Can we make a guess about when this bug will be solved and the new date picker will be released? I need this component :)

**Comment by ugurdoksan** [comment]
The locale problem is solved but, when I select the date, it selects the previous day.
For Example in TR Locale:
I select: 08.09.2018 (8 September 2018)
It selects: 07.09.2018 (9 September 2018)

The code is the same with #116.

`dpStartDate = new DatePicker( "" );
dpStartDate.setPlaceholder( "Start Date" );
dpStartDate.setLocale( new Locale( "tr", "TR" ) );`
