### ISSUE TITLE
DatePicker display date in wrong locale

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-date-picker-flow#135]
`DatePicker` shows the date with English locale despite the locale set:

<img width="214" alt="screenshot 2018-10-09 at 14 09 21" src="https://user-images.githubusercontent.com/851745/46668657-60f1e580-cbcd-11e8-9eaa-caeba72c834f.png">

It should display as `31/12/2018` instead.

Demo at: [heruan/vaadin-spring-demo](https://github.com/heruan/vaadin-spring-demo/blob/ee1fe13db2934e25fc798abfd99f965f488428bb/src/main/java/to/lova/vaadin/spring/DatePickerDemo.java)

Possibly related to #129.

**Comment by steffen-harbich-itc** [comment]
I am having the same issue in Flow v12.0.3. The DatePicker does not adapt to the locale set via setLocale nor to the locale set via UI.getCurrent().setLocale in case the Locale is language only, e.g. new Locale("de"). However, when I apply new Locale("de", "DE") then the date format is fine but the texts in the picker popup are still in English.

**Comment by heruan** [comment]
@steffen-harbich-itc I'm closing this as it's working in 12.0.5 and 13.0.0.alpha4, did you try these? I'm not sure *when* this was fixed, as it didn't get much attention; good thing it's fixed now (you can verify on my demo project).

**Comment by steffen-harbich-itc** [comment]
True, with 12.0.5 the date format is also working for me. Thanks!

However, I am a little confused why internationalization of texts etc in the calendar is not done automatically - for at least some major languages like Chinese, Japanese, German, French etc. So everyone who has a multi-language application is doing the same thing (on a global view): providing translations for languages XYZ.

**Comment by jpatera** [comment]
I've been recently facing similar problems (Vaadin 11.x - 12.0.5), mostly browsing with  Chrome 71.0.3578.80 .
1. Set DatePicker with new Locale("cs", "CZ").
2. Open page (form) for the firt time -> date is in correct CZ format like 28.1.2019 .
3. Open another app view and back -> date is rendered as 1/28/2019 .

Fortunatelly I found a workaround by setting the component's locale in onAttach() like this:

@Route(...)
@SpringComponent
@UIScope
public class SomeView extends VerticalLayout...
  private static final Locale czLocale = new Locale("cs", "CZ");
  ...
  @Override
  protected void onAttach(AttachEvent attachEvent) {
      datePicker,setLocale(czLocale);
  }

It coud be quite probbably workaronded better and more generally, but I can live with this for now.
Might be helpful.

**Comment by mariovonleitmeritz** [comment]
I am having the same issue like [jpatera](https://github.com/vaadin/vaadin-date-picker-flow/issues/135#issuecomment-464911345) in Flow v13.0.6
