### ISSUE TITLE
DatePickerValidationPageIT::invalidLocale test fails

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-date-picker-flow#166]
The test fails on line:
https://github.com/vaadin/vaadin-date-picker-flow/blob/master/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerValidationPageIT.java#L114

**Comment by ZheSun88** [comment]
duplicated with https://github.com/vaadin/vaadin-date-picker-flow/issues/165, closed
