### ISSUE TITLE
Setting theme cuases JS exception

### ISSUE THREAD

**Issue by jmycka** [vaadin/vaadin-date-picker-flow#171]
Setting theme for DatePicker element causes JS exception:
`TypeError: this._setTheme is not a function`

Problem occurs with web component v3.3.3 (platform release 13.0.3)

See code below to reproduce error:
`final DatePicker dp = new DatePicker();
dp.getElement().getThemeList().add("small");`

**Comment by ZheSun88** [comment]
Hi, 
This is the repo for `date-picker` flow integration. I will move this issue to the webcomponent repo so that you can get proper help.

**Comment by ZheSun88** [comment]
Issue moved to [vaadin/vaadin-date-picker #651](https://github.com/vaadin/vaadin-date-picker/issues/651) via [**ZenHub**](https://www.zenhub.com/)
