### ISSUE TITLE
Clear button doesn't work on mobile screen

### ISSUE THREAD

**Issue by rubic69** [vaadin/vaadin-date-picker-flow#202]
When enabling mobile device view in Chrome DevTools and also on mobile itself, clear button appear not working at all.

How to reproduce:
- Simply add DatePicker field to the view.
- Enable that clear button would be visible
- Open view and select value
- Try to tap on clear button

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-date-picker/pull/682
