### ISSUE TITLE
From V.14.0.6 the DatePicker field with BeanValidationBinder on @NotNull bean property is initialy set by flow as invalid

### ISSUE THREAD

**Issue by darmro** [vaadin/vaadin-date-picker-flow#203]
### Environment
Windows 10, localization PL-pl, Java 8, Firefox or Chrome

### Description
For:
1) Vaadin DatePicker field with BeanValidationBinder on @NotNull bean property
2) No readBean() and no validate() being initialy called
3) No data being initialy entered to the field

In v. 14.0.5 the field was initialy rendered ok (as a normal valid required field).
From Vaadin v 14.0.6 the DatePicker field is initialy rendered by flow as an invalid field (red) with no required attribute (and no required indicator). It should be mentioned that in the same time the NumberField on similar @NotNull bean property is initialy rendered ok as a valid required field.

### Expected outcome
Initialy when no data was entered the DatePicker field should be rendered as a normal valid and required field, just like others fields, eg. NumberField on similar @NotNull bean property.

### Steps to reproduce
1. Get Vaadin Starter Project (Spring Boot).
2. Add simple binder form in MainView:
```
Binder<AData> binder = new BeanValidationBinder<>(AData.class);

NumberField numberField = new NumberField("Number");
binder.bind(numberField, "number");
add(numberField);

DatePicker dateField = new DatePicker("Date");
binder.bind(dateField, "date");
add(dateField);
```
3. For simple bean:
```
public class AData {
	@NotNull
	private Integer number;

	@NotNull
	private LocalDate date;

	public Integer getNumber() {
		return number;
	}
	public void setNumber(Integer number) {
		this.number = number;
	}
	public LocalDate getDate() {
		return date;
	}
	public void setDate(LocalDate date) {
		this.date = date;
	}
}
```

4. Run in new 14.0.8 and then the same on 14.0.5.

**Comment by igormilina** [comment]
This regression bug is quite serious IMO. We cannot ship application to our customers that displays forms with date fields that are initially rendered as "invalid" (painted red). And we have lots of forms with lots of required date fields.

**Comment by darmro** [comment]
This issue is also in new 14.0.9

**Comment by tomivirkki** [comment]
Agreed, looks serious. We'll take a look asap
