### ISSUE TITLE
Can't set date format

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-date-picker-flow#30]
There seems to be no way to set the input format for the date field

**Comment by pleku** [comment]
In the I18N Object there is:
```javascript
      formatDate: function(date) {
        // Sugar Date expects a native date. The `date` is in format `{ day: ..., month: ..., year: ... }`
        return Sugar.Date.format(Sugar.Date.create(date), '{short}');
      },
```

But this should be exposed more easily and we should have a demo running of just changing the format. Our current I18N demo doesn't touch the format.

**Comment by pleku** [comment]
This has already been done.
