### ISSUE TITLE
Label will not be shown

### ISSUE THREAD

**Issue by svenruppert** [vaadin/vaadin-date-picker-flow#35]
If I set the label of a DatePicker (birthday) in the same way I am doing it with a TextField, it is not shown.

````
    firstName.setId(TF_FIRST_NAME_ID);
    firstName.setLabel(resolve(TF_FIRST_NAME_CAPTION));

//SNIPP
    status.setId(CB_STATUS_ID);
    status.setLabel(resolve(CB_STATUS_CAPTION));
    status.setItems(CustomerStatus.values());

    birthday.setId(DF_BIRTHDAY_ID);
    birthday.setLabel(resolve(DF_BIRTHDAY_CAPTION));
````
<img width="703" alt="bildschirmfoto 2018-02-16 um 06 39 23" src="https://user-images.githubusercontent.com/2665330/36294996-c3d4338a-12e4-11e8-821f-048fbb611559.png">

**Comment by denis-anisimov** [comment]
I cannot reproduce this.
May be this was an issue on the client side component.
But now it works as it should.
We have a demo for this use case.
Please see
https://github.com/vaadin/vaadin-date-picker-flow/blob/master/src/test/java/com/vaadin/flow/component/datepicker/demo/DatePickerView.java#L71

I've checked that the label works as expected.
Please reopen the ticket if it doesn't work for you in the latest release.
