### ISSUE TITLE
DatePicker is considered invalid when I bind it with a validator.

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-date-picker-flow#4]
@ZheSun88 commented on [Thu Sep 21 2017](https://github.com/vaadin/flow/issues/2471)

when i use binder with DatePicker, the default date is somehow missing after i implement the validator.

Before, i use binder without validator, 
`binder.forField(lastTasted).bind(Review::getDate, Review::setDate);`

the default date is there as it is shown in the image
![image](https://user-images.githubusercontent.com/31067185/30697594-40f7deb4-9ee8-11e7-8352-1884175faa0c.png)

But after i implement the validator,
```
 binder.forField(lastTasted)
                .withValidator(date -> date != null,
                        "The date should be in dd/MM/yyyy format.")
                .bind(Review::getDate, Review::setDate);
```
the default date is disappeared from the DatePicker, which suppose to be there.
![image](https://user-images.githubusercontent.com/31067185/30697859-f947d96a-9ee8-11e7-90b5-3ff6354ea7d3.png)
(But, if i choose a date from the DatePicker, no need to save or delete, just cancel the dialog, the DatePicker can work as normal)

temporary solution:
Use DatePicker.setValue() before binds the DatePicker with binder validator.

---

@pleku commented on [Fri Sep 22 2017](https://github.com/vaadin/flow/issues/2471#issuecomment-331357360)

@ZheSun88 don't expect people to know what happens on _save_, _delete_ or _cancel_, e.g. what code gets triggered in `Binder` on those. There are several options actually.

Please provide links to the actual case instead or real code example to reproduce and investigate the issue, thanks.

**Comment by denis-anisimov** [comment]
I cannot reproduce this behavior for many reasons:
- DatePicker has no default value nowadays. I'm not sure what you mean by default value here at all actually.
- If I set the value explicitly to the date picker then everything works in the same way with or without validator.

So the question what's the `default value` term here.
If you mean that you are using the default CTOR `new DatePicker();` then see the very first observation: `null` value is set explicitly from the server side and the `DatePicker` has no any value with the default CTOR.

There is a comment related to the bug description: please use exact terms which has no connotations. The term `default value` is not clear here at all: is it the value which you have set explicitly or this is the value which is set implicitly somehow.

With the non-default CTOR I don't see any validation errors or such.

I believe the behavior described in the ticket was related to the fact of client-side value usage.
As a result the client side sent to the server side the value which has been considered as invalid for some reason.

Nowadays the server side overrides the client side value (with the default CTOR) and there is no any value and it satisfies the validator.

Another question is : should we use the current date as a default value for `DatePicker`   or no any date at all (as it's done now). But this is another ticket if any.

Please reopen this ticket if it still valid for you.

Current resolution : Works for me.
