### ISSUE TITLE
SPIKE: Investigate formatting date picker selected date using a client side library

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-date-picker-flow#45]
Based on the issue https://github.com/vaadin/vaadin-date-picker-flow/issues/38, investigate how well it could work to integrate https://momentjs.com/ or https://sugarjs.com/dates/#/formatting to the client side for handling the formatting of the dates the user inputs.
Starting point is that
- format and locale should be definable from the server side Java API
  - the default locale of the UI should be applied, but that doesn't need investigation
- the client side needs to customize the `i18n.parseDate` and `i18n.formatDate` functions to apply the locale and the format

**Comment by pekam** [comment]
I've experimented now with sugar.js, and with this library it is at least really easy to solve the original problem in the ticket, which was about default date formats based on locale. With a simple js-connector we can pass the server-side `Locale` to `formatDate()` and `parseDate()` and use sugar.js there to handle the conversions.

However, this works only when using some of the few locale-specific date formats of sugar.js. For `DatePicker`  there are practically two options, which include only the date without the time:
 - `{short}`, eg. `02/03/2018`
 - `{medium}`, eg. `16 maggio 2018` (using Italian locale)

[You can also implement any kind of format with sugar.js](https://sugarjs.com/dates/#/Formatting), but then sugar doesn't know anymore how to convert the string back to a date, so implementing `parseDate()` to support arbitrary format is not possible.

So even if we use this external library, we could only offer these two formats to users. Also a couple of notes:
 - sugar.js supports 17 major locales
    - if it gets unsupported language, a js-error is thrown, but we can take care of that, and the datepicker doesn't break but just uses the default locale
 - using the `{medium}` format would override the month-strings defined in the `DatePickerI18n` object

**Conclusion about sugar.js** (so far)
We can easily provide the locale specific formatting for most locales (so the users will have eg. month and day in the correct order), but we can't offer more than a couple of options for the formats.

**Comment by pekam** [comment]
Actually, we are not restricted to the two formats mentioned above. We can of course implement more formats by handling converting them to the formats accepted by sugar.js and back. So we can at least allow to change the separator in the `{short}` format, for example to dots. And sugar.js would still handle the locale-based ordering of day and month.

**Comment by pekam** [comment]
Pushed sugar.js experiments to a branch:
https://github.com/vaadin/vaadin-date-picker-flow/commit/e7f06b59c1818a563dae48a462fed591401e8a22

**Comment by pekam** [comment]
Tested that `moment.js` knows how to parse dates back and forth using the same format, which would make it easier to support more arbitrary date formats. But then it's the developers responsibility to provide all the data to the format. For example if the format provides only the weekday, moment.js doesn't necessarily return the correct date, but some date that matches the weekday.

**Comment by pleku** [comment]
Follow up on https://github.com/vaadin/vaadin-date-picker-flow/issues/38
