### ISSUE TITLE
DatePicker with a non default format formats to wrong date.

### ISSUE THREAD

**Issue by caalador** [vaadin/vaadin-date-picker-flow#84]
I want to display 6th May --> 06/05/2018 in french and 30th May --> 30/05/2018 

I've got 05/06/2018 selected as 05th June (format correct but display date != java date) and 5/30/2018 selected as 30 May (wrong format but display date = Java date)

```
@BodySize(height = "100vh", width = "100vw")
@HtmlImport("styles/shared-styles.html")
@Route("date")
@Theme(Lumo.class)
public class DatePickerView extends VerticalLayout {

    private DatePicker dateDialog = new DatePicker("date Dialog");
    private DatePicker dateDialogToday = new DatePicker("date Dialog Today");

    public DatePickerView() {
        LocalDate date30May = LocalDate.of(2018, Month.MAY, 30);
        LocalDate date06May = LocalDate.of(2018, Month.MAY, 6);

        dateDialog.setLocale(Locale.FRANCE);
        dateDialog.setValue(date06May);

        dateDialogToday.setLocale(Locale.FRANCE);
        dateDialogToday.setValue(date30May);

        add(dateDialog,dateDialogToday);

        setClassName("main-layout");
    }

}
```

**Comment by sblommers** [comment]
How is this closed? This still a problem for Edge browsers. Using flow 1.0.0 and date-picker 1.0.0

**Comment by ZheSun88** [comment]
Hi @sblommers , I have tried with `vaadin.version` 10.0.1 which contains `date-picker` 1.0.0
just using the provided code in this ticket and changing the locale to `dateDialog.setLocale(new Locale("nl", "NL"));`. the behavior looks correct to me, you can check the image below.
![datepicker-84](https://user-images.githubusercontent.com/31067185/42804826-c10e196e-89b2-11e8-9b61-a0aff0c70499.gif)

as this ticket has been closed, you can open a new one for your case for more discussion.

**Comment by sblommers** [comment]
Thank you for testing this for me, seems like this might even be a browser version specific problem, we tested using a virtualbox image from M$, we eventually used FRANCE locale using **/** instead of **-** these work fine on all platforms. If I get some spare time i'll test it again more thoroughly. 

If I have findings I'll create a new ticket and post there.
