### ISSUE TITLE
DatePickerI18n is not working

### ISSUE THREAD

**Issue by jcgueriaud** [vaadin/vaadin-date-picker-flow#88]
Hello,

I've just clone the repository and run "mvn jetty:run -PrunTests".
The "Internationalized date picker" case is not working (and there is no error during the tests).
See screenshot below. Perhaps it has been introduced in RC1 (on beta 10 it was working).

![capture du 2018-06-04 13-59-27](https://user-images.githubusercontent.com/25199660/40916327-99b2c59c-67ff-11e8-8373-18087d197449.png)

Thanks

**Comment by jcgueriaud** [comment]
To test and make the screenshot, I clone this repository after the changes (because dateConnector has been changed oldLocale = 'en-US' ). So I think I've got the last changes.

**Comment by ZheSun88** [comment]
So it works not? @jcgueriaud
